services:
  proxy:
    container_name: proxy
    build:
      context: ./proxy-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    depends_on:
      - proxy
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"